version: "3.8"

services:
  users_service:
    build: ./users_service
    container_name: users_service
    restart: always
    networks:
      - backend_net

  orders_service:
    build: ./orders_service
    container_name: orders_service
    restart: always
    environment:
      - USER_SERVICE_URL=http://users_service:8001
    networks:
      - backend_net

  gateway_service:
    build: ./gateway_service
    container_name: gateway_service
    restart: always
    environment:
      - USER_SERVICE_URL=http://users_service:8001
      - ORDER_SERVICE_URL=http://orders_service:8002
    ports:
      - "8080:8080"
    networks:
      - backend_net

  frontend_service:
    build: ./frontend_service
    container_name: frontend_service
    restart: always
    ports:
      - "3000:80"
    networks:
      - backend_net
    depends_on:
      - gateway_service

networks:
  backend_net:
    driver: bridge